### ISSUE TITLE
feature suggestion: deleting rows from a tabel

### ISSUE THREAD

**Issue by manuelarriaga** [BastiaanBergman/tabel#9]
**Feature suggestion:** it would be helpful to be able to delete rows from a dataset.

**Possible interfaces:**

1) pandas does it through the [.drop()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html) method.

2) An alternative would be implementing a `__delitem__()` method for tabel objects, which would support (arguably) more Pythonic use such as what you get with built-in types (e.g., lists and dictionaries):

>>> l = ["a","b","c"]
>>> del l[1]
>>> l
['a','c']
>>> d = {'species': 'dog'}
>>> del d['species']
>>> d
{}

We could extend this interface to work with Tabel objects:

>>> t = tabel.Tabel( {'name': ['ally', 'mike', 'sue'], 'age': [30, 31, 32] } )
>>> t
 name  |  age
 --------+--------
ally      |  30
mike    | 31
sue      | 32
3 rows ['<U4', '<i8']
>>> del t[1] # delete second row
>>> t
 name  |  age
 --------+--------
ally      |  30
sue      | 32
2 rows ['<U4', '<i8']
>>> del t[0:2] # delete first two rows
>>> t
 name  |  age
 --------+--------
0 rows 

Either alternative would work and would fulfill an important need to remove data from a dataset.

**Suggestion:**

Using either interface above, we could implement this as a wrapper around [numpy.delete()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html). We would call numpy.delete() on all the columns making up the tabel. Doing so would have the benefit of effortlessly supporting the different argument types that numpy.delete() supports. We could identify rows to be removed by a single integer (remove row x), by a list of integers (remove rows 3, 5 and 9) or a slice object (remove rows [3:10]).

**Related question:**

How to support removing columns from a dataset?

**Comment by BastiaanBergman** [comment]
I like it, good idea. I think we should do columns too. How does one delete columns from pandas? It does get a little tricky in that case because the delete item method needs to figure out whether a column or a row is meant. For that we best keep the same logic as used in the getitem method.

**Comment by manuelarriaga** [comment]
Hi Bastiann, here is a first go at this. All the best, M

**Comment by BastiaanBergman** [comment]
Manuel, Thanks! Looks good! Can you please also add some tests for this? Look in test/test_tabel.py for examples and just add a new class to the list. All tests will be performed by invoking `pytest`.

**Comment by manuelarriaga** [comment]
Hi Bastiaan, here is the pull request! Please take a look at the tests, not sure they are as thorough as you want them to be: #11.

**Comment by BastiaanBergman** [comment]
Fixed with Manuel's PR.
